/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "YOUR_AWS_REGION", // e.g., "us-east-1"
    "aws_cognito_region": "YOUR_AWS_REGION",
    "aws_user_pools_id": "COGNITO_USER_POOL_ID_FROM_OUTPUT",
    "aws_user_pools_web_client_id": "COGNITO_CLIENT_ID_FROM_OUTPUT",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "ApiGateway", // This is a friendly name for your API
            "endpoint": "API_ENDPOINT_URL_FROM_OUTPUT",
            "region": "YOUR_AWS_REGION"
        }
    ]
};

export default awsmobile;